import { Router } from "express";
import { authRoutesPublic } from "./public/auth.routes";
import { authRoutesPrivate } from "./private/auth.routes";
import { proyectosRoutes } from "./private/proyectos.routes";
import { dashboardRoutes } from "./private/dashboard.routes";
import { convocatoriasRoutes } from "./private/convocatorias.routes";
import { catalogosRoutes } from "./private/catalogos.routes";
import { gruposRoutes } from "./private/grupos.routes";
import { usuariosRoutes } from "./private/usuarios.routes";
import { productosRoutes } from "./private/productos.routes";
import { tiposDocumentoRoutes } from "./private/tipos-documento.routes";
import { rolesRoutes } from "./private/roles.routes";
import { permisosRoutes } from "./private/permisos.routes";
import { evaluacionesRoutes } from "./private/evaluaciones.routes";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutesPublic);
apiRoutes.use("/auth", authRoutesPrivate);
apiRoutes.use("/proyectos", proyectosRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/convocatorias", convocatoriasRoutes);
apiRoutes.use("/catalogos", catalogosRoutes);
apiRoutes.use("/grupos-investigacion", gruposRoutes);
apiRoutes.use("/usuarios", usuariosRoutes);
apiRoutes.use("/productos", productosRoutes);
apiRoutes.use("/tipos-documento", tiposDocumentoRoutes);
apiRoutes.use("/roles", rolesRoutes);
apiRoutes.use("/permisos", permisosRoutes);
apiRoutes.use("/evaluaciones", evaluacionesRoutes);
